version: "3.3"

services:
  main-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: main-server
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    # gpus: all  # Jetson GPU access
    runtime: nvidia
