# ======================
# Stage 1: Build stage
# ======================
FROM continuumio/miniconda3:25.3.1-1 AS builder

WORKDIR /app
ARG ENV_NAME=pii-leakage

# Create env and install deps
RUN conda create -n $ENV_NAME python=3.10 -y && conda clean -afy

# Activate env and install dependencies
COPY requirements.txt .
RUN /bin/bash -c "source activate $ENV_NAME && pip install -r requirements.txt"

COPY . .
RUN /bin/bash -c "source activate $ENV_NAME && pip install -e ."

# ======================
# Stage 2: Runtime image
# ======================
FROM continuumio/miniconda3:25.3.1-1 AS runtime

WORKDIR /app
ARG ENV_NAME=pii-leakage

# Copy environment
COPY --from=builder /opt/conda/envs/$ENV_NAME /opt/conda/envs/$ENV_NAME

# Copy project code
COPY configs ./configs
COPY src ./src
COPY examples ./examples

# Default entrypoint (conda run)
ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "pii-leakage", "python"]
CMD ["--help"]
